apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  template:
    metadata:
      name: auth-pod
      labels:
        app: myapp
        type: auth-api

    spec:
      containers:
        - name: auth-app
          image: auth-app:v1
          ports:
             - containerPort: 8888
          env: 
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://kube-auth-db:3307/db-auth?serverTimezone=UTC
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root          
  replicas: 1
  selector:
    matchLabels:
      app: myapp
      type: auth-api
---
apiVersion: v1
kind: Service
metadata:
  name: kube-auth
spec:
  type: NodePort
  ports:
    - targetPort: 8888
      port: 80
      nodePort: 30006
  selector:
    app: myapp
    type: auth-api
---
kind: Service
apiVersion: v1
metadata:
  name: auth-service
spec:
  selector:
    app: myapp
    type: auth-api
  type: ClusterIP
  ports:
     - port: 8888
       targetPort: 8888    
