apiVersion: apps/v1
kind: Deployment
metadata:
  name: communication-service
spec:
  template:
    metadata:
      name: communication-pod
      labels:
        app: myapp
        type: communication-api

    spec:
      containers:
        - name: communication-app
          image: communication-app:v1
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://kube-communication-db:3309/db-communication-service?serverTimezone=UTC
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root

  replicas: 1
  selector:
    matchLabels:
      app: myapp
      type: communication-api
---
kind: Service
apiVersion: v1
metadata:
  name: communication-service
spec:
  selector:
    app: myapp
    type: communication-api
  type: ClusterIP
  ports:
     - port: 8083
       targetPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: kube-communication
spec:
  type: NodePort
  ports:
    - targetPort: 8083
      port: 80
      nodePort: 30008
  selector:
    app: myapp
    type: communication-api      