apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deploy
spec:
  template:
    metadata:
      name: front-pod
      labels:
        app: myapp
        type: front-api

    spec:
      containers:
        - name: front-app
          image: front-user-app:v3
          ports:
            - containerPort: 8000
  replicas: 1
  selector:
    matchLabels:
      app: myapp
      type: front-api
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  ports:
    - targetPort: 8000
      port: 8089
      nodePort: 30005
  selector:
    app: myapp
    type: front-api
  